name: rafpored
description: Flutter application for showing scheduled exams

dependencies:
  fluro: "^1.1.0"
  intl: "^0.15.6"
  http: "^0.11.3+16"
  shared_preferences: "^0.4.1"
  flutter_local_notifications: "^0.2.9"
  #small_calendar: "^0.4.0"
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
      - assets/img/loading.gif
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300